name: 'Build Image'

on:
  workflow_dispatch:
    inputs:
      bunVersion:
        description: 'Bun Version'
        required: true
        type: string
      setLatest:
        description: 'Set "latest" tag'
        required: true
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}},value=v${{ inputs.bunVersion }}
            type=semver,pattern=v{{major}}.{{minor}},value=v${{ inputs.bunVersion }}
            type=semver,pattern=v{{major}},value=v${{ inputs.bunVersion }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=v${{ inputs.bunVersion }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ inputs.bunVersion }}
            type=semver,pattern={{major}},value=v${{ inputs.bunVersion }}
            type=raw,value=latest,enable=${{ inputs.setLatest }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VARIANT=${{ inputs.bunVersion }}
          file: .devcontainer/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}